version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
- package-ecosystem: "maven"
    directory: "vertx-template-engines/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "vertx-web-graphql/"
    schedule:
      interval: "daily"
      
